AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sns-abstraction-layer

  Sample SAM Template for sns-abstraction-layer

Resources:
#  HelloWorldFunction:
#    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#    Properties:
#      CodeUri: hello_world/
#      Handler: app.lambda_handler
#      Runtime: python3.9
#      Architectures:
#        - x86_64
#      Events:
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /hello
#            Method: get

  # Lambda layer definitions
  AWSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AWSLayer
      Description: |
        Layer containing modules for encapsulating AWS services.
      ContentUri: lib/layers/aws/
      CompatibleRuntimes:
        - python3.9
